version: '3.8'

services:

  sut:
    image: your-org/sut:stable-tag # replace with your image
    depends_on:
      - vote
      - result
      - worker
    networks:
      - front-tier

  vote:
    image: your-org/vote:stable-tag # replace with your image
    ports: ["8080:80"] # change host port if needed
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    image: your-org/result:stable-tag # replace with your image
    ports: ["8081:80"] # change host port if needed
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    image: your-org/worker:stable-tag # replace with your image
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "secureuser" # change as needed
      POSTGRES_PASSWORD: "securepassword" # change as needed
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
