version: '3.8'

services:

  sut:
    image: front
    depends_on:
      - vote
      - result
      - worker
    networks:
      - front-tier

  vote:
    image: app
    ports: ["8080:80"] 
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    image: result
    ports: ["8081:80"] 
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    image: backend
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "User@123"
      POSTGRES_PASSWORD: "password@123"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
